# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gsp < Formula
  desc ""
  homepage "https://github.com/Open-SL/gsp"
  version "0.1.1"

  on_macos do
    url "https://github.com/Open-SL/gsp/releases/download/v0.1.1/gsp_0.1.1_darwin_all.tar.gz"
    sha256 "1610a9680a8e0e021fc38944d302915ff16ffe2cf5e2da91202b2c2d6918c105"

    def install
      bin.install "gsp"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Open-SL/gsp/releases/download/v0.1.1/gsp_0.1.1_linux_amd64.tar.gz"
        sha256 "2da072e127decc585c767012c914c8825f18e46054900bb56630c6e53dc600fe"

        def install
          bin.install "gsp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Open-SL/gsp/releases/download/v0.1.1/gsp_0.1.1_linux_arm64.tar.gz"
        sha256 "3215819cd4d16756537a380d4b5d1838f856d8cc81c931d217312bc15ca72d2a"

        def install
          bin.install "gsp"
        end
      end
    end
  end
end
